### ISSUE TITLE
Should this package use Immutable value objects or not

### ISSUE THREAD

**Issue by nyamsprod** [bakame-php/http-structured-fields#1]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

I have been working on package to handle [RFC8941](https://www.rfc-editor.org/rfc/rfc8941.html) via value objects with a pragmatic approach using value objects. This package is heavily inspired by [gapple structured fields](https://github.com/gapple/structured-fields/) 

Currently you can do the following:

```php
use Bakame\Http\StructuredFields\Item;

$fields = Item::from("/terms", ['rel' => "copyright", 'anchor' => '#foo']);
echo $fields->toHttpValue(), PHP_EOL; //display "/terms";rel="copyright";anchor="#foo"

$fields->parameters()->set("anchor", "#bar");
echo $fields->toHttpValue(), PHP_EOL; //display "/terms";rel="copyright";anchor="#bar"
```

Should it switch to use immutable object instead 🤔  ? Is it worth the effort ? As I believe the current public API is more straightforward to use ?

@gapple @kelunik what is your opinion ?

**Comment by kelunik** [comment]
@nyamsprod The main advantage would be caching the parsed values, no?

**Comment by nyamsprod** [comment]
I stumble upon an edge cases that will trigger a `UnexpectedValueException` because of the mutable aspect of the package **but** it's an edge case that is covered via throwing a `SerializationError`.

https://github.com/bakame-php/http-structured-fields/blob/master/src/Parameters.php#L92

So  even thought I prefer immutable object, in this case, using immutable collections would make the package less appealing to use. Also I believe this package should be use by other package maintainers who can decorate it's behaviour around an immutable API. 

For instance a SetCookie class could use the package internally. It would be immutable while this package stays mutable:

```php
<?php

function toStructuredField(Cookie $cookie): string
{
    $parameters = [];
    if ($cookie->expiresAt !== 0) {
        $parameters['expires'] = $cookie->expiresAt;
    }

    if ('' !== $cookie->path) {
        $parameters['path'] = $cookie->path;
    }

    if ('' !== $cookie->domain) {
        $parameters['domain'] = $cookie->domain;
    }

    if ($cookie->secure) {
        $parameters['secure'] = $cookie->secure;
    }

    if ($cookie->httpOnly) {
        $parameters['httponly'] = $cookie->httpOnly;
    }

    if ('' !== $cookie->sameSite) {
        $parameters['samesite'] = $cookie->sameSite;
    }

    return Dictionary::fromAssociative([
       $cookie->name => Item::from(new Token($cookie->value), $parameters),
    ])->toHttpValue();
}
```

This method can be used in an immutable value object while the package stays mutable 🤔

**Comment by nyamsprod** [comment]
The package will remain mutable as making everything immutable bring no extra improvement for now. I may revisit this in a future release
