### ISSUE TITLE
v2 docs feedback

### ISSUE THREAD

**Issue by simonrjones** [bakame-php/http-structured-fields#14]
A few comments on your v2 docs at https://github.com/bakame-php/http-structured-fields/tree/master/docs

The docs seem good. It's certainly nice to have examples on pages with details of what you expect to be returned. The docs seem to be a mix of some quite in-depth docs alongside more starter intro docs. It's hard to understand the later docs without more experimentation with the code - though I'm sure they are good when you need to dig deeper into how this works.

https://github.com/bakame-php/http-structured-fields/blob/master/docs/00-intro.md
- `$field = DataType::List->parse($fieldValue);` sounds like this returns a list of items, so call the variable $fields

https://github.com/bakame-php/http-structured-fields/blob/master/docs/02-parsing-serializing.md
- Examples of each of the data types (List, Dictionary, etc) would make them easier to understand. I appreciate that may exist on the RFC but if you can give an real world examples that would be aid understanding.
- I found the comment phrase `returns a tuple as n array...` complicated to read. This appears to return an array, I'd just call it that. I'm not familiar with the term tuple in PHP programming.
- Typo: "accessible via their names or thir indices" -> their indices

It would be useful to document how to test if a data item exists, it seems to be as simple as calling `isset($permissions['geolocation'])`

**Comment by simonrjones** [comment]
One further thing. If HTTP Structured Fields is so new, is it safe to actually use this with any existing HTTP response headers or should this only be used for creating new HTTP headers?

If you have any references to lists of existing HTTP headers that do follow the HTTP Structured Fields format it would be useful to include that here.

**Comment by nyamsprod** [comment]
I have applied all the changes
> It would be useful to document how to test if a data item exists, it seems to be as simple as calling isset($permissions['geolocation'])

For this I did nothing as it is explain in the documentation 

> All containers objects implement PHP `IteratorAggregate`, `Countable` and `ArrayAccess` interfaces. Their members can be accessed using the following shared methods

**Comment by nyamsprod** [comment]
I changed my mind and added other examples to the documentation so all your remarks have been taking care of. Thanks for the input and the help.
